import { CommunitySummary } from "./client";

export const MOCK_COMMUNITIES: CommunitySummary[] = [
  {
    id: 1,
    name: "Green Island",
    parish: "Hanover",
    nearest_landmark: "Green Island Harbour",
    lat: "18.3833",
    lng: "-78.2667",
    report_count: 5,
    severe_houses: 23,
    no_water: 1,
    no_light: 1,
    limited_access: 1,
    has_high_risk: 1,
    severity_score: 8.5,
    severity: "severe",
    last_report_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Negril",
    parish: "Westmoreland",
    nearest_landmark: "Negril Beach",
    lat: "18.2677",
    lng: "-78.3497",
    report_count: 8,
    severe_houses: 17,
    no_water: 1,
    no_light: 0,
    limited_access: 1,
    has_high_risk: 1,
    severity_score: 7.2,
    severity: "severe",
    last_report_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Montego Bay",
    parish: "St James",
    nearest_landmark: "Sam Sharpe Square",
    lat: "18.4762",
    lng: "-77.8939",
    report_count: 12,
    severe_houses: 7,
    no_water: 0,
    no_light: 0,
    limited_access: 0,
    has_high_risk: 0,
    severity_score: 4.5,
    severity: "moderate",
    last_report_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Lucea",
    parish: "Hanover",
    nearest_landmark: "Lucea Clock Tower",
    lat: "18.4508",
    lng: "-78.1739",
    report_count: 3,
    severe_houses: 4,
    no_water: 0,
    no_light: 1,
    limited_access: 0,
    has_high_risk: 0,
    severity_score: 3.8,
    severity: "moderate",
    last_report_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Savanna-la-Mar",
    parish: "Westmoreland",
    nearest_landmark: "Savanna-la-Mar Market",
    lat: "18.2197",
    lng: "-78.1328",
    report_count: 6,
    severe_houses: 24,
    no_water: 1,
    no_light: 1,
    limited_access: 1,
    has_high_risk: 1,
    severity_score: 8.0,
    severity: "severe",
    last_report_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Black River",
    parish: "St Elizabeth",
    nearest_landmark: "Black River Bridge",
    lat: "18.0258",
    lng: "-77.8489",
    report_count: 4,
    severe_houses: 0,
    no_water: 0,
    no_light: 0,
    limited_access: 0,
    has_high_risk: 0,
    severity_score: 1.5,
    severity: "low",
    last_report_at: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Santa Cruz",
    parish: "St Elizabeth",
    nearest_landmark: "Santa Cruz Town Square",
    lat: "18.0903",
    lng: "-77.7433",
    report_count: 7,
    severe_houses: 5,
    no_water: 0,
    no_light: 1,
    limited_access: 0,
    has_high_risk: 0,
    severity_score: 4.0,
    severity: "moderate",
    last_report_at: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Reading",
    parish: "St James",
    nearest_landmark: "Reading Town Center",
    lat: "18.4322",
    lng: "-77.7858",
    report_count: 2,
    severe_houses: 0,
    no_water: 0,
    no_light: 0,
    limited_access: 0,
    has_high_risk: 0,
    severity_score: 1.2,
    severity: "low",
    last_report_at: new Date().toISOString(),
  },
];
